const prefix = 'APP';


export const FETCH_FEATURED_MOVIES = `${prefix}.FETCH_FEATURED_MOVIES`;
export const SET_FEATURED_MOVIES = `${prefix}.SET_FEATURED_MOVIES`;
export const FEATCH_FEATURED_MOVIES_REQUEST = `${prefix}.FEATCH_FEATURED_MOVIES_REQUEST`;
export const SET_FEATURED_MOVIES_REQUEST = `${prefix}.SET_FEATURED_MOVIES_REQUEST`;
export const SET_FEATURED_MOVIES_ERROR = `${prefix}.SET_FEATURED_MOVIES_ERROR`;
export const FETCH_MOVIE_DETAILS =`${prefix}.FETCH_MOVIE_DETAILS`;
export const SET_MOVIE_DETAILS =`${prefix}.SET_MOVIE_DETAILS`;
export const SET_MOVIE_DETAILS_ERROR = `${prefix}.SET_MOVIE_DETAILS_ERROR`;
export const FETCH_SEARCHED_MOVIES =`${prefix}.FETCH_SEARCHED_MOVIES`;
export const SET_SEARCHED_MOVIES =`${prefix}.SET_SEARCHED_MOVIES`;
export const SET_SEARCHED_MOVIES_ERROR = `${prefix}.SET_SEARCHED_MOVIES_ERROR`;
export const FETCH_GENRE_LIST =`${prefix}.FETCH_GENRE_LIST`;
export const SET_GENRE_LIST =`${prefix}.SET_GENRE_LIST`;
